### ISSUE TITLE
Access-Control-Allow-Origin问题，YAAW不能下载

### ISSUE THREAD

**Issue by halida** [binux/ThunderLixianExporter#41]
用YAAW下载，设置了rpcpath到http://192.168.10.60:6800/jsonrpc，下载的时候提示：

    XMLHttpRequest cannot load http://192.168.10.60:6800/jsonrpc?tm=1421139430491. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://dynamic.cloud.vip.xunlei.com' is therefore not allowed access. The response had HTTP status code 401.

还有就是看代码才知道YAAW是代表用rpc方式下载，能不能改一下提示为YAAW(area-rpc)？

**Comment by binux** [comment]
YAAW 是指 https://github.com/binux/yaaw ，请按照 YAAW 的设置，开启 `--rpc-allow-origin-all`

**Comment by halida** [comment]
@binux 谢谢，原来是rpc后端需要允许。

**Comment by halida** [comment]
@binux 对了，我aria rpc后端加上了用户密码，在设置里面如何写？

**Comment by binux** [comment]
http://username:password@192.168.10.60:6800/jsonrpc

**Comment by halida** [comment]
@binux 谢谢！可以正常工作了。最好可以在文档里面加上说明。
