### ISSUE TITLE
迅雷离线页面没有设置按键了

### ISSUE THREAD

**Issue by yh127** [binux/ThunderLixianExporter#45]
迅雷离线页面右上角没有那个设置按键了，是脚本问题还是迅雷的问题？怎么设置 JSON-RPC 呀？

**Comment by insurgo222** [comment]
遇到同样问题

**Comment by tofuliang** [comment]
迅雷本身的问题,临时救急可以用开发者工具直接改 localstorage

Ewing Chao <notifications@github.com>于2016年9月22日周四 下午6:42写道：

**Comment by tomatohello** [comment]
迅雷本身的问题,临时救急可以用开发者工具直接改 localstorage

请问，怎么改 localstorage，新手上路，请指点，谢谢。
