### ISSUE TITLE
请问离线下载插件是不是不能使用了

### ISSUE THREAD

**Issue by causlayer** [binux/ThunderLixianExporter#47]
我已经在Tampermonkey中安装了插件，也正常设置了http://token:123456@127.0.0.1:6800/jsonrpc,
然后在取回本地里选择YAAW,可我在web控制台显示是错误，并没有下载视频。
我的系统是mac os 10.12.1，chrome浏览器版本 56.0.2902.0 dev (64-bit)，使用aria2c可以正常在百度云里下载文件，配置应该是没有问题的。不知道是不是需要额外的设置，如需要请告知，谢谢。

**Comment by binux** [comment]
aria2 日志

**Comment by causlayer** [comment]
实际下载地址为：ed2k://%7Cfile%7C%25E6%2597%25A0%25E8%2580%25BB%25E5%25AE%25B6%25E5%25BA%25AD.Shameless.US.S07E04.%25E4%25B8%25AD%25E8%258B%25B1%25E5%25AD%2597%25E5%25B9%2595.HDTVrip.1024x576.mp4%7C552869501%7C26ca1d181ec86844b27f4f05e712714e%7Ch%3Dulvnff2t3rtlhch7liuop3qbfuv2zgny%7C/
日志：
-> % aria2c

11/02 23:35:54 [NOTICE] IPv4 RPC: listening on TCP port 6800

11/02 23:35:54 [NOTICE] IPv6 RPC: listening on TCP port 6800

11/02 23:37:22 [NOTICE] Download GID#1da8c21a553b36aa not complete: /Users/apple/Downloads/无耻家庭.Shameless.US.S07E04.中英字幕.HDTVrip.1024x576.mp4

11/02 23:41:39 [NOTICE] Download GID#b84674f53e35eb00 not complete: /Users/apple/Downloads/无耻家庭.Shameless.US.S07E04.中英字幕.HDTVrip.1024x576.mp4

11/02 23:44:41 [NOTICE] Emergency shutdown sequence commencing...

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
1da8c2|ERR |       0B/s|/Users/apple/Downloads/无耻家庭.Shameless.US.S07E04.中英字幕.HDTVrip.1024x576.mp4

配置文件里关于bt这块的配置：
## BT/PT下载相关 ##

# 当下载的是一个种子(以.torrent结尾)时, 自动开始BT任务, 默认:true
#follow-torrent=true
# BT监听端口, 当端口被屏蔽时使用, 默认:6881-6999
listen-port=51413
# 单个种子最大连接数, 默认:55
#bt-max-peers=55
# 打开DHT功能, PT需要禁用, 默认:true
enable-dht=false
# 打开IPv6 DHT功能, PT需要禁用
#enable-dht6=false
# DHT网络监听端口, 默认:6881-6999
#dht-listen-port=6881-6999
# 本地节点查找, PT需要禁用, 默认:false
#bt-enable-lpd=false
# 种子交换, PT需要禁用, 默认:true
enable-peer-exchange=false
# 每个种子限速, 对少种的PT很有用, 默认:50K
#bt-request-peer-speed-limit=50K
# 客户端伪装, PT需要
peer-id-prefix=-TR2770-
user-agent=Transmission/2.77
# 当种子的分享率达到这个数时, 自动停止做种, 0为一直做种, 默认:1.0
seed-ratio=0
# 强制保存会话, 即使任务已经完成, 默认:false
# 较新的版本开启后会在任务完成后依然保留.aria2文件
#force-save=false
# BT校验相关, 默认:true
#bt-hash-check-seed=true
# 继续之前的BT任务时, 无需再次校验, 默认:false
bt-seed-unverified=true
# 保存磁力链接元数据为种子文件(.torrent文件), 默认:false
bt-save-metadata=true
