### ISSUE TITLE
用书签添加的怎么删掉

### ISSUE THREAD

**Issue by Nriver** [binux/ThunderLixianExporter#48]
先用了书签,想换成UserScript.结果界面上出现了两个小齿轮和两个取回本地的按钮 请问书签添加的那个怎么删掉?

**Comment by binux** [comment]
不可能啊，你不点书签不就完了。

**Comment by Nriver** [comment]
![6](https://cloud.githubusercontent.com/assets/6752679/21191410/fa9fefd4-c25f-11e6-897b-ff10917ae3ef.jpg)
书签添加的那个去不掉 缓存清掉书签也删掉都没用 我把TamperMonkey的打开所有的东西就变成两个了2333

**Comment by binux** [comment]
书签(bookmark)是你地址栏下方的快捷网址。

你不点它根本不会执行。
你不点击书签，它根本不会执行。
你不点击书签，它根本不会添加任何东西。

「缓存清掉书签也删掉都没用」书签和缓存有什么关系？
