### ISSUE TITLE
支持新版离线空间

### ISSUE THREAD

**Issue by pxia** [binux/ThunderLixianExporter#49]
这两天网页版离线用不了，其实他们出了一个新版：http://lixian.xunlei.com/xl9/space.html
说是旧版在维护，但感觉早晚旧版要淘汰，应该适应一下新版。

**Comment by binux** [comment]
用旧版，这个新版根本没有取回本地功能，没有可以导出的东西。

**Comment by pxia** [comment]
旧版已经好几天不能用了，感觉是在强推新版。。但新版这个取回本地的按钮根本没有作用。。
我服迅雷

**Comment by binux** [comment]
http://dynamic.cloud.vip.xunlei.com/ 不能用吗？我现在用着好好的啊

**Comment by pxia** [comment]
你用代理了吗？我因为在美国，以前是要挂日本代理才能打开页面，否则跳转kankan.com。这两天挂着代理也502

**Comment by binux** [comment]
我在英国，直接开
